# Generated by Django 4.2.3 on 2023-07-23 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoProject', '0002_city_host_location_propertytype_revokedtoken_state_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('phone', models.IntegerField()),
                ('bio', models.TextField()),
                ('profile_image', models.URLField()),
                ('dob', models.DateField(null=True)),
            ],
        ),
    ]
