# Generated by Django 4.2.3 on 2023-07-19 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourista_backend', '0002_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
