# Generated by Django 4.2.3 on 2023-07-22 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourista_backend', '0008_property_city_property_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='location',
        ),
    ]
