# Generated by Django 4.2.3 on 2023-07-21 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoProject', '0004_location_propertytype_property'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='hosted_sice',
        ),
        migrations.AddField(
            model_name='property',
            name='hosted_since',
            field=models.DateTimeField(null=True),
        ),
    ]
