# Generated by Django 4.2.3 on 2023-07-21 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoProject', '0003_alter_host_created_at_alter_host_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.TextField()),
                ('city', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property', models.TextField()),
                ('total_bedrooms', models.IntegerField()),
                ('summary', models.TextField()),
                ('address', models.TextField()),
                ('price', models.IntegerField()),
                ('hosted_sice', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoProject.host')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoProject.location')),
                ('property_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoProject.propertytype')),
            ],
        ),
    ]
